### ISSUE TITLE
After downloading the data, use the txt files in the data folder, and process the CFP feature by feature_extraction.py.

### ISSUE THREAD

**Issue by Viki520** [anonymity5033/MTANet#4]
CFP process in data/wav/tammy_1_07.wav ... (It may take some times)
Traceback (most recent call last):
File "feature_extraction.py", line 269, in
W, _, _ = cfp_process(wavpath, sr=8000)
File "feature_extraction.py", line 216, in cfp_process
y, sr = load_audio(fpath, sr=sr)
File "feature_extraction.py", line 159, in load_audio
x, fs = sf.read(filepath)
File "/home/zhangjunwei/miniconda3/envs/TONet/lib/python3.8/site-packages/soundfile.py", line 285, in read
with SoundFile(file, 'r', samplerate, channels,
File "/home/zhangjunwei/miniconda3/envs/TONet/lib/python3.8/site-packages/soundfile.py", line 658, in init
self._file = self._open(file, mode_int, closefd)
File "/home/zhangjunwei/miniconda3/envs/TONet/lib/python3.8/site-packages/soundfile.py", line 1216, in _open
raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'data/wav/tammy_1_07.wav': System error.

Hello, I encountered the above error when dealing with the CFP function in the first step.Is this a data error or a problem with my system?
Can someone help me?Can briefly write down the specific steps?Thank you

**Comment by Annmixiu** [comment]
Hi, I am very happy that you pay attention to my work. According to the error statement you provided, I speculate that there are the following two reasons:
(i) The audio format or library version you downloaded does not match;
(ii) The audio named tammy_1_07.wav is corrupted in your place. To further verify this problem, I suggest you to do a separate listening analysis, that is, to test the readability and audibility of the error audio with Adobe and other playback software;
It is worth mentioning that I am using Python3.7, but I am concerned that you are using a higher version and may need to do other library matching as well. Hope this solves your problem. Good luck.

**Comment by Viki520** [comment]
Thank you very much for your reply！I have solved the above problem，the reason I found the error was because there was a problem with the file name under my path。But at the same time, I discovered new problems：In line 263 of the feature_extraction.py, the magfile is given.It asks for an npy file but I didn't find any npy files or magfile folders from the MIR1K and Medley-DB datasets. I don't know how this npy was obtained. I would appreciate it if you could take time out of your busy schedule to answer my questions
The following table describes the error message：
Traceback (most recent call last):
  File "feature_extraction.py", line 270, in <module>
    np.save(magfile, W)
  File "<__array_function__ internals>", line 6, in save
  File "/home/zhangjunwei/miniconda3/envs/TONet/lib/python3.7/site-packages/numpy/lib/npyio.py", line 525, in save
    file_ctx = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/cfp_360_new/tammy_1_07.npy'

**Comment by Viki520** [comment]
I've fixed the above issue thanks I found out that the error was caused by not creating a folder named cfp_360_new under data/

**Comment by Annmixiu** [comment]
Ok, your problem-solving skills are great! In addition, I want to tell you that "No such file or directory" type errors are usually problems with the path and file existence.

**Comment by Viki520** [comment]
Hello, I'm very sorry, I still have a question, I found that I have to use some files in MedleyDB during training, but I can't download the MedleyDB dataset, can you give me a download link through a way like Baidu Netdisk？Thank you very much.
